# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: toml -*-

#                             VVVVVV  minimum `pixi` version
"$schema" = "https://pixi.sh/v0.36.0/schema/manifest/schema.json"

[project]
name = "occt-feedstock"
version = "3.52.3"  # conda-smithy version used to generate this file
description = "Pixi configuration for conda-forge/occt-feedstock"
authors = ["@conda-forge/occt"]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "linux-ppc64le", "osx-64", "win", "win-64"]

[dependencies]
conda-build = ">=24.1"
conda-forge-ci-setup = "4.*"
rattler-build = "*"

[tasks]
[tasks.inspect-all]
cmd = "inspect_artifacts --all-packages"
description = "List contents of all packages found in rattler-build build directory."
[tasks.build]
cmd = "rattler-build build --recipe recipe"
description = "Build occt-feedstock directly (without setup scripts), no particular variant specified"
[tasks."build-linux_64_variantall"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_variantall.yaml"
description = "Build occt-feedstock with variant linux_64_variantall directly (without setup scripts)"
[tasks."inspect-linux_64_variantall"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_variantall.yaml"
description = "List contents of occt-feedstock packages built for variant linux_64_variantall"
[tasks."build-linux_64_variantnovtk"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_variantnovtk.yaml"
description = "Build occt-feedstock with variant linux_64_variantnovtk directly (without setup scripts)"
[tasks."inspect-linux_64_variantnovtk"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_variantnovtk.yaml"
description = "List contents of occt-feedstock packages built for variant linux_64_variantnovtk"
[tasks."build-linux_aarch64_variantall"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_aarch64_variantall.yaml"
description = "Build occt-feedstock with variant linux_aarch64_variantall directly (without setup scripts)"
[tasks."inspect-linux_aarch64_variantall"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_aarch64_variantall.yaml"
description = "List contents of occt-feedstock packages built for variant linux_aarch64_variantall"
[tasks."build-linux_aarch64_variantnovtk"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_aarch64_variantnovtk.yaml"
description = "Build occt-feedstock with variant linux_aarch64_variantnovtk directly (without setup scripts)"
[tasks."inspect-linux_aarch64_variantnovtk"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_aarch64_variantnovtk.yaml"
description = "List contents of occt-feedstock packages built for variant linux_aarch64_variantnovtk"
[tasks."build-linux_ppc64le_"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_ppc64le_.yaml"
description = "Build occt-feedstock with variant linux_ppc64le_ directly (without setup scripts)"
[tasks."inspect-linux_ppc64le_"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_ppc64le_.yaml"
description = "List contents of occt-feedstock packages built for variant linux_ppc64le_"
[tasks."build-osx_64_variantall"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_64_variantall.yaml"
description = "Build occt-feedstock with variant osx_64_variantall directly (without setup scripts)"
[tasks."inspect-osx_64_variantall"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_variantall.yaml"
description = "List contents of occt-feedstock packages built for variant osx_64_variantall"
[tasks."build-osx_64_variantnovtk"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_64_variantnovtk.yaml"
description = "Build occt-feedstock with variant osx_64_variantnovtk directly (without setup scripts)"
[tasks."inspect-osx_64_variantnovtk"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_variantnovtk.yaml"
description = "List contents of occt-feedstock packages built for variant osx_64_variantnovtk"
[tasks."build-osx_arm64_variantall"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_variantall.yaml"
description = "Build occt-feedstock with variant osx_arm64_variantall directly (without setup scripts)"
[tasks."inspect-osx_arm64_variantall"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_variantall.yaml"
description = "List contents of occt-feedstock packages built for variant osx_arm64_variantall"
[tasks."build-osx_arm64_variantnovtk"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_variantnovtk.yaml"
description = "Build occt-feedstock with variant osx_arm64_variantnovtk directly (without setup scripts)"
[tasks."inspect-osx_arm64_variantnovtk"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_variantnovtk.yaml"
description = "List contents of occt-feedstock packages built for variant osx_arm64_variantnovtk"
[tasks."build-win_64_variantall"]
cmd = "rattler-build build --recipe recipe -m .ci_support/win_64_variantall.yaml"
description = "Build occt-feedstock with variant win_64_variantall directly (without setup scripts)"
[tasks."inspect-win_64_variantall"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/win_64_variantall.yaml"
description = "List contents of occt-feedstock packages built for variant win_64_variantall"
[tasks."build-win_64_variantnovtk"]
cmd = "rattler-build build --recipe recipe -m .ci_support/win_64_variantnovtk.yaml"
description = "Build occt-feedstock with variant win_64_variantnovtk directly (without setup scripts)"
[tasks."inspect-win_64_variantnovtk"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/win_64_variantnovtk.yaml"
description = "List contents of occt-feedstock packages built for variant win_64_variantnovtk"

[feature.smithy.dependencies]
conda-smithy = "*"
shellcheck = "*"
[feature.smithy.tasks.build-locally]
cmd = "python ./build-locally.py"
description = "Build packages locally using the same setup scripts used in conda-forge's CI"
[feature.smithy.tasks.smithy]
cmd = "conda-smithy"
description = "Run conda-smithy. Pass necessary arguments."
[feature.smithy.tasks.rerender]
cmd = "conda-smithy rerender"
description = "Rerender the feedstock."
[feature.smithy.tasks.lint]
cmd = "conda-smithy lint --conda-forge recipe"
description = "Lint the feedstock recipe"

[environments]
smithy = ["smithy"]
# This is a copy of default, to be enabled by build_steps.sh during Docker builds
# __PLATFORM_SPECIFIC_ENV__ = []
